#### Numpy: Package for Multi-Dimensional Array

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
sample_matrix=np.array(list_of_lists)

In [4]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(3,2)

array([[0.54065536, 0.51311078],
       [0.17536786, 0.33593571],
       [0.12005892, 0.77361415]])

In [20]:
np.random.randn(3,2)

array([[ 1.46569154, -0.13340675],
       [-0.01667218,  0.02786601],
       [-0.70303222, -0.26155534]])

In [21]:
np.random.randint(34,100)

95

In [22]:
np.random.randint(34,100,50)

array([53, 66, 54, 71, 91, 63, 94, 84, 99, 62, 82, 76, 70, 86, 59, 52, 81,
       68, 47, 77, 74, 98, 46, 71, 60, 92, 93, 62, 71, 52, 59, 82, 91, 60,
       95, 86, 78, 44, 79, 56, 97, 79, 67, 82, 70, 67, 41, 77, 88, 85])

#### One Dimensional Array

In [23]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
rand_array=np.random.randint(0,99,20)
rand_array

array([68, 71, 76, 35, 25,  1, 14, 14, 85, 15, 84, 71, 29, 72, 31, 10, 93,
        6, 55, 26])

In [25]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
rand_array.min()

1

In [27]:
rand_array.argmin()

5

In [28]:
sample_array.max()

29

In [29]:
sample_array.dtype

dtype('int32')

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
sample_array[3]

13

In [34]:
sample_array[3:7]

array([13, 14, 15, 16])

In [35]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [36]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [38]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [39]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [40]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

#### Two Dimensional Array

In [41]:
import numpy as np

In [42]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [43]:
sample_matrix[2][3]

7

In [44]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [45]:
sample_matrix[2]

array([56, 76, 24,  7])

In [46]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [47]:
  sample_matrix[1,3]

33

In [48]:
sample_matrix[0:2,2]    
#sample_matrix[(0,1),2]

array([ 1, 21])

In [49]:
sample_matrix[2]

array([56, 76, 24,  7])

In [50]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [51]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [52]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [53]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [54]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [55]:
np.max(sample_array)

19

In [56]:
np.min(sample_array)

1

In [57]:
np.argmax(sample_array)

18

In [58]:
np.argmin(sample_array)

0

In [59]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [60]:
np.mean(sample_array)

10.0

In [61]:
np.std(sample_array)

5.477225575051661

In [62]:
np.var(sample_array)

30.0

In [63]:
array=np.random.randn(3,4)
array

array([[ 0.09619964, -0.77084743, -0.81387539, -0.62388985],
       [-1.53005768, -3.12182783,  1.75165119, -1.10757071],
       [ 0.94234187,  1.16587594,  0.76512571,  0.69128009]])

In [64]:
np.round(array,decimals=3)

array([[ 0.096, -0.771, -0.814, -0.624],
       [-1.53 , -3.122,  1.752, -1.108],
       [ 0.942,  1.166,  0.765,  0.691]])

In [65]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')